export const RANDOM_QUOTE_REQUEST = 'RANDOM_QUOTE_REQUEST';
export const RANDOM_QOUTE_SUCCESS = 'RANDOM_QUOTE_SUCCESS';
export const RANDOM_QOUTE_FAIL = 'RANDOM_QUOTE_FAIL';


export const RANDOM_QUOTE_AUTHOR_REQUEST = 'RANDOM_QUOTE_AUTHOR_REQUEST';
export const RANDOM_QUOTE_AUTHOR_SUCCESS = 'RANDOM_QUOTE_AUTHOR_SUCCESS';
export const RANDOM_QUOTE_AUTHOR_FAIL = 'RANDOM_QUOTE_AUTHOR_FAIL';